services:
  backend:
    build: ./apps/backend
    env_file:
      - ./.env
      - ./apps/backend/.env
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    volumes:
      - ./apps/backend/storage:/app/storage
  frontend:
    build: ./apps/frontend
    env_file:
      - ./.env
      - ./apps/frontend/.env
    environment:
      - VITE_API_URL=${FRONTEND_API_URL:-http://localhost:4000}
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      - backend
